"""
The heuristic solver in this file is almost entirely generated by Claude,
based on the CP-SAT solver in boxfit.py which has had much more love and care
put into it. Unfortunately the exact solver is way too slow.

The two strategies seem alright for tabular content but no guarantees for others.

Claude output starts:

Pairwise/star coordinate descent alternative to the CP-SAT box-fitting solver.

Every constraint in this problem is naturally a coupled pair of edges that
must stay `gap` apart:
  * a cell's own (x0, x1) and (y0, y1) -- must stay >= min_size apart
  * two touching cells' facing edges -- must stay >= gap apart (whichever of
    the 4 possible facings currently applies)

The base move optimizes one such pair at a time: given two coupled edges, do
an exact small 2-D search over both simultaneously, holding everything else
fixed, and take whichever combination is cheapest.

That's not enough when an edge is shared by *more than one* constraint on the
same side -- e.g. one wide cell sitting below two narrower cells side by side.
The wide cell's top edge (y0) is coupled separately to each of the two cells'
bottom edges (y1) above it, via two different constraints. Solving those two
pairs one at a time only ever asks "what's best for this edge and *one*
neighbor", so it can get stuck: moving the shared edge further would let
*both* neighbors settle into cheaper positions, but neither pairwise solve on
its own sees that combined benefit, and the sweep just ping-pongs between two
locally-cheap-but-jointly-bad states.

To fix that we add a second kind of move, `solve_star`: whenever an edge is
tied via multiple *currently binding* constraints to distinct partner edges
that are all on the same side of the gap (all of them need `partner >= v +
gap`, or all need `partner <= v - gap`), we jointly search over the shared
edge together with every one of its partners at once. For a fixed candidate
value of the shared edge, each partner's optimal value/cost is independent of
the others (only the feasible range depends on the shared edge), so this is
solved exactly and efficiently with a prefix/suffix-min sweep per partner,
not a combinatorial search. We alternate star sweeps with the plain pairwise
sweeps until a full round of both changes nothing.
"""
import numpy as np
import random
from .boxfit import build_cost_image

def _can_touch(ci, cj, max_expand):
    """Can these two boxes possibly end up overlapping given the max
    expansion on every side? Used to prune the O(n^2) pair list."""
    xi0, yi0, xi1, yi1 = ci
    xj0, yj0, xj1, yj1 = cj
    x_reach = (xi1 + max_expand) > (xj0 - max_expand) and (xj1 + max_expand) > (xi0 - max_expand)
    y_reach = (yi1 + max_expand) > (yj0 - max_expand) and (yj1 + max_expand) > (yi0 - max_expand)
    return x_reach and y_reach


_LO = ('x0', 'y0')  # edges where a larger value means the cell shrinks


def _suffix_best(vals, costs):
    """Sort by value ascending; for each position return the (cost, value)
    achieving the minimum cost among all values >= that position's value."""
    order = np.argsort(vals)
    vs, cs = vals[order], costs[order].astype(float)
    n = len(vs)
    best_cost = np.empty(n)
    best_val = np.empty(n, dtype=vs.dtype)
    rc, rv = np.inf, vs[-1]
    for i in range(n - 1, -1, -1):
        if cs[i] <= rc:
            rc, rv = cs[i], vs[i]
        best_cost[i] = rc
        best_val[i] = rv
    return vs, best_cost, best_val


def _prefix_best(vals, costs):
    """Sort by value ascending; for each position return the (cost, value)
    achieving the minimum cost among all values <= that position's value."""
    order = np.argsort(vals)
    vs, cs = vals[order], costs[order].astype(float)
    n = len(vs)
    best_cost = np.empty(n)
    best_val = np.empty(n, dtype=vs.dtype)
    rc, rv = np.inf, vs[0]
    for i in range(n):
        if cs[i] <= rc:
            rc, rv = cs[i], vs[i]
        best_cost[i] = rc
        best_val[i] = rv
    return vs, best_cost, best_val


def solve_boxfit(cells, cost, cost_downscale=1, solve_downscale=1, max_expand=25, max_push=15,
          min_size=15, gap=1, w_edge=1, w_dev=1, w_dev_grow=None, max_passes=100, max_time=60, workers=8):
    """
    Args mirror the CP-SAT version. Returns just new_cells: np.ndarray (N,4)
    of optimized [x0,y0,x1,y1] in pixel coordinates.
    """
    cells = np.asarray(cells, int)
    n = len(cells)
    if n == 0:
        return np.zeros((0, 4))
    Hn, Wn = cost.shape

    if w_dev_grow is None:
        w_dev_grow = 0.5 * w_dev

    def s(v):
        return int(round(v / solve_downscale))

    max_expand_s = max(1, round(max_expand / solve_downscale))
    max_push_s = max(1, round(max_push / solve_downscale))
    min_size_s = max(1, round(min_size / solve_downscale))
    gap_s = max(0, round(gap / solve_downscale))

    # ---- per-cell state: original position, movement domain, cost tables ----
    orig, domain, cur = {}, {}, {}
    vcost, hcost = {}, {}
    for k, (x0, y0, x1, y1) in enumerate(cells):
        ox0, oy0, ox1, oy1 = s(x0), s(y0), s(x1), s(y1)
        for e, o in (('x0', ox0), ('y0', oy0), ('x1', ox1), ('y1', oy1)):
            orig[(k, e)] = cur[(k, e)] = o
        domain[(k, 'x0')] = (ox0 - max_expand_s, ox0 + max_push_s)
        domain[(k, 'y0')] = (oy0 - max_expand_s, oy0 + max_push_s)
        domain[(k, 'x1')] = (ox1 - max_push_s, ox1 + max_expand_s)
        domain[(k, 'y1')] = (oy1 - max_push_s, oy1 + max_expand_s)

        # edge-cost lookup tables, assuming (ceteris paribus) the cell's
        # other pair of edges stays where it started
        ny0, ny1 = np.clip([round(y0 / cost_downscale), round(y1 / cost_downscale)], 0, Hn)
        nx0, nx1 = np.clip([round(x0 / cost_downscale), round(x1 / cost_downscale)], 0, Wn)
        vcost[k] = cost[ny0:ny1, :].sum(axis=0) if ny1 > ny0 else np.zeros(Wn, int)
        hcost[k] = cost[:, nx0:nx1].sum(axis=1) if nx1 > nx0 else np.zeros(Hn, int)

    # ---- every constraint is a pair of edges that must stay `gap` apart ----
    # 'options': one (left, right) choice for a hard constraint (min-size),
    # or 4 possible (left, right) choices for a non-overlap constraint, of
    # which at least one must hold.
    constraints = []
    for k in range(n):
        constraints.append({'gap': min_size_s, 'options': [((k, 'x0'), (k, 'x1'))]})
        constraints.append({'gap': min_size_s, 'options': [((k, 'y0'), (k, 'y1'))]})
    for i in range(n):
        for j in range(i + 1, n):
            if not _can_touch(cells[i], cells[j], max_expand):
                continue
            constraints.append({'gap': gap_s, 'options': [
                ((i, 'x1'), (j, 'x0')), ((j, 'x1'), (i, 'x0')),
                ((i, 'y1'), (j, 'y0')), ((j, 'y1'), (i, 'y0')),
            ]})

    touching = {}  # edge -> constraint indices it participates in
    for cidx, c in enumerate(constraints):
        for left, right in c['options']:
            touching.setdefault(left, []).append(cidx)
            touching.setdefault(right, []).append(cidx)

    def active_option(c):
        """Which (left, right) choice currently satisfies this constraint."""
        held = [(l, r) for l, r in c['options'] if cur[l] + c['gap'] <= cur[r]]
        return held[0] if held else c['options'][0], len(held)

    def bounds(v, skip_cidxs):
        """Feasible range for edge v given every other constraint's current
        state (skip_cidxs are the constraint(s) being jointly solved right
        now, so they shouldn't constrain themselves)."""
        if isinstance(skip_cidxs, int):
            skip_cidxs = {skip_cidxs}
        lo, hi = domain[v]
        for cidx in touching.get(v, []):
            if cidx in skip_cidxs:
                continue
            c = constraints[cidx]
            (left, right), n_held = active_option(c)
            if n_held > 1:
                continue  # already satisfied another way -- no constraint from here
            if v == left:
                hi = min(hi, cur[right] - c['gap'])
            elif v == right:
                lo = max(lo, cur[left] + c['gap'])
        return lo, hi

    def cost_of(v, vals):
        k, e = v
        table = vcost[k] if e in ('x0', 'x1') else hcost[k]
        idx = np.clip((vals * solve_downscale) // cost_downscale, 0, len(table) - 1)
        delta = vals - orig[v]
        if e in _LO:
            shrink, grow = np.clip(delta, 0, None), np.clip(-delta, 0, None)
        else:
            grow, shrink = np.clip(delta, 0, None), np.clip(-delta, 0, None)
        return w_edge * table[idx] + w_dev * shrink + w_dev_grow * grow

    def solve_pair(cidx):
        # Try every option this constraint allows (just 1 for min-size, up
        # to 4 for non-overlap) and keep the cheapest one that's actually
        # achievable -- can't just trust whichever option currently holds,
        # since two cells that start out merely touching (0 gap) satisfy
        # *none* of the 4 options yet, and the right one to fix isn't
        # necessarily the first in the list.
        c = constraints[cidx]
        best = None
        for left, right in c['options']:
            lo_l, hi_l = bounds(left, cidx)
            lo_r, hi_r = bounds(right, cidx)
            if lo_l > hi_l or lo_r > hi_r:
                continue
            vals_l, vals_r = np.arange(lo_l, hi_l + 1), np.arange(lo_r, hi_r + 1)
            totals = cost_of(left, vals_l)[:, None] + cost_of(right, vals_r)[None, :]
            feasible = (vals_l[:, None] + c['gap']) <= vals_r[None, :]
            if not feasible.any():
                continue
            totals = np.where(feasible, totals, np.inf)
            i, j = np.unravel_index(np.argmin(totals), totals.shape)
            if best is None or totals[i, j] < best[0]:
                best = (totals[i, j], left, right, int(vals_l[i]), int(vals_r[j]))
        if best is None:
            return False
        _, left, right, new_l, new_r = best
        changed = new_l != cur[left] or new_r != cur[right]
        cur[left], cur[right] = new_l, new_r
        return changed

    def solve_star(v):
        # Find every constraint currently binding on v (single-option, not
        # already satisfied another way), split by which side of the gap v
        # is on. When >=2 of them put v on the *same* side with *distinct*
        # partner edges, jointly optimize v together with all of those
        # partners at once -- this is the case a plain pairwise sweep can't
        # solve: one shared edge (e.g. a wide cell's top edge) constrained
        # separately by several neighbors (e.g. two cells above it).
        incident = touching.get(v, [])
        if len(incident) < 2:
            return False

        groups = {'left': [], 'right': []}
        for cidx in incident:
            c = constraints[cidx]
            (left, right), n_held = active_option(c)
            if n_held > 1:
                continue
            if v == left:
                groups['left'].append((cidx, right, c['gap']))
            elif v == right:
                groups['right'].append((cidx, left, c['gap']))

        role = 'left' if len(groups['left']) >= len(groups['right']) else 'right'
        items = groups[role]
        if len(items) < 2:
            return False
        item_cidxs = {it[0] for it in items}

        # v's own domain, restricted by every *other* (non-star) constraint
        lo_v, hi_v = domain[v]
        for cidx in incident:
            if cidx in item_cidxs:
                continue
            c = constraints[cidx]
            (left, right), n_held = active_option(c)
            if n_held > 1:
                continue
            if v == left:
                hi_v = min(hi_v, cur[right] - c['gap'])
            elif v == right:
                lo_v = max(lo_v, cur[left] + c['gap'])
        if lo_v > hi_v:
            return False

        vs = np.arange(lo_v, hi_v + 1)
        total = cost_of(v, vs).astype(float)
        partner_plans = []  # (partner_edge, best_val_for_each_v)

        for cidx, partner, gap in items:
            lo_p, hi_p = bounds(partner, cidx)
            if lo_p > hi_p:
                return False
            pv = np.arange(lo_p, hi_p + 1)
            pc = cost_of(partner, pv)

            if role == 'left':
                # need partner >= v + gap
                vs_sorted, best_cost, best_val = _suffix_best(pv, pc)
                idx = np.searchsorted(vs_sorted, vs + gap, side='left')
                feasible = idx < len(vs_sorted)
                idx_c = np.clip(idx, 0, len(vs_sorted) - 1)
            else:
                # need partner <= v - gap
                vs_sorted, best_cost, best_val = _prefix_best(pv, pc)
                idx = np.searchsorted(vs_sorted, vs - gap, side='right') - 1
                feasible = idx >= 0
                idx_c = np.clip(idx, 0, len(vs_sorted) - 1)

            cost_arr = np.where(feasible, best_cost[idx_c], np.inf)
            val_arr = best_val[idx_c]
            total = total + cost_arr
            partner_plans.append((partner, val_arr))

        if not np.isfinite(total).any():
            return False

        best_i = int(np.argmin(total))
        new_v = int(vs[best_i])
        changed = new_v != cur[v]
        cur[v] = new_v
        for partner, val_arr in partner_plans:
            new_p = int(val_arr[best_i])
            if new_p != cur[partner]:
                changed = True
            cur[partner] = new_p
        return changed

    pair_order = list(range(len(constraints)))
    star_order = [v for v, cidxs in touching.items() if len(cidxs) >= 2]

    for _ in range(max_passes):
        random.shuffle(pair_order)
        changed_pair = any([solve_pair(cidx) for cidx in pair_order])
        random.shuffle(star_order)
        changed_star = any([solve_star(v) for v in star_order])
        if not (changed_pair or changed_star):
            break

    return np.array([[cur[(k, 'x0')] * solve_downscale, cur[(k, 'y0')] * solve_downscale,
                       cur[(k, 'x1')] * solve_downscale, cur[(k, 'y1')] * solve_downscale]
                      for k in range(n)]), None


if __name__ == '__main__':
    rng = np.random.default_rng(1)
    H, W = 400, 500
    cost = rng.integers(1, 3, size=(H, W)).astype(np.int32)
    gutter = 6
    for gx in range(0, W, 60):
        cost[:, max(0, gx - gutter // 2):gx + gutter // 2] = 0
    for gy in range(0, H, 50):
        cost[max(0, gy - gutter // 2):gy + gutter // 2, :] = 0

    cells = []
    for gx in range(0, W - 60, 60):
        for gy in range(0, H - 50, 50):
            jitter = rng.integers(-8, 8, size=4)
            cells.append([gx + jitter[0], gy + jitter[1], gx + 55 + jitter[2], gy + 45 + jitter[3]])
    cells = np.array(cells)

    new_cells = solve_boxfit(cells, cost, max_expand=10, max_push=10,
                       min_size=15, gap=1, w_dev=0.5, w_dev_grow=0.25)
    print(new_cells[:5])