[sift]  # not recommended to change these SIFT defaults
# max number of detected SIFT features
nfeatures = 10000
contrast_threshold = 0.04
edge_threshold = 10
# good for max_alignment_dim=800
sigma = 1.6
# threshold for Lowe's ratio test (discarding non-discriminative features)
lowes_ratio_threshold = 0.7

[flann]
# number of search trees in FLANN for feature matching
num_trees = 5

[prefiltering]
# number of nearest neighbors selected in prefiltering (usually 12)
k = 12
# number of bytes in pHash, which can be visualized as a square black and white image with a width of sqrt(phash_bytes*8)
phash_bytes = 32
# whether to use PCA representation of thumbnail-sized image for prefiltering or to use phash representation
descriptor = "pca"  # phash | pca
# downscaled image size for PCA
pca_image_size = 64
# maximum number of pca components, value fed into PCA() will be min(len(images)//2, config["prefiltering"]["pca_components"])
pca_components = 64

[ransac_graph]
# maximum offset in pixels for a feature to be considered an inlier
pixel_threshold = 3.0
# minimum number of matches to return a valid alignment
min_matches = 100
# maximum number of RANSAC iterations, affects speed
max_iters = 5000
# minimum confidence level for RANSAC, affects speed
confidence = 0.999 

[ransac_final]
# same as above
pixel_threshold = 3.0
min_matches = 30
max_iters = 5000
confidence = 0.999

[bspline]
enabled = true
cells_on_shorter_side = 4

[page_alignment]
# minimum number of pages with a transform to root for track to be considered valid
min_support = 3
# downscaled page size used for alignment, in pixels
max_alignment_dim = 800  

[transform_propagation]
# hop penalty when determining shortest paths
hop_penalty = 0.05

[transform_limits]
# maximum translation (relative to image size)
max_translation = 0.2
# scale limits (multiplicative)
min_scale = 0.8
max_scale = 1.2
# maximum rotation (in degrees)
max_rotation_deg = 15

[debug]
enabled = false